alias cb="git branch | grep \*"
alias commit="git commit -am $1"
alias commitall="git add . && git commit -am $1"
alias push="git push origin"
alias pull="git pull origin"
alias fetch="git fetch origin"